### ISSUE TITLE
pywintypes.com_error: (-2147221231, 'ClassFactory 无法供应请求的类', None, None)

### ISSUE THREAD

**Issue by Sword20140414** [130347665/pyDmSoft#1]
`Traceback (most recent call last):
  File "d:/Seraph/example.py", line 1316, in <module>
    m_dm = DM()
  File "d:/Seraph/example.py", line 52, in __init__
    self.dm = win32com.client.Dispatch('dm.dmsoft')
  File "D:\Seraph\venv\lib\site-packages\win32com\client\__init__.py", line 117, in Dispatch
    dispatch, userName = dynamic._GetGoodDispatchAndUserName(dispatch, userName, clsctx)
  File "D:\Seraph\venv\lib\site-packages\win32com\client\dynamic.py", line 106, in _GetGoodDispatchAndUserName
    return (_GetGoodDispatch(IDispatch, clsctx), userName)
  File "D:\Seraph\venv\lib\site-packages\win32com\client\dynamic.py", line 89, in _GetGoodDispatch
    IDispatch, None, clsctx, pythoncom.IID_IDispatch
pywintypes.com_error: (-2147221231, 'ClassFactory 无法供应请求的类', None, None)`

有没有碰到这样的问题，是如何解决的呀

**Comment by 130347665** [comment]
你是使用32位的python吗?
